// Generated by CoffeeScript 1.7.1
(function() {
  var DATA_MEMBERS_URL, Member, build, icon;

  DATA_MEMBERS_URL = 'data/members.json';

  build = function(klass) {
    return jQuery("<div></div>").addClass(klass);
  };

  icon = function(klass) {
    return jQuery("<i></i>").addClass("fa fa-" + klass);
  };

  Member = (function() {
    function Member(obj) {
      this.name = obj.name;
      this.realname = obj.realname;
      this.email = obj.email;
      this.avatar = obj.avatar;
      this.weibo = obj.weibo;
      this.zhihu = obj.zhihu;
      this.$members = jQuery('.page-members .members');
    }

    Member.prototype.render = function() {
      this.$elm = build('member').appendTo(this.$members).hide().fadeIn();
      this.$avatar = build('pie avatar s100 bordered').appendTo(this.$elm);
      this.$avatar_img = jQuery("<img />").attr('src', this.avatar).appendTo(this.$avatar);
      this.$name = build('name bold').html(this.name).appendTo(this.$elm);
      this.$email = build('email').html(this.email).prepend(icon('envelope-o')).appendTo(this.$elm);
      if (this.weibo) {
        this.$weibo = build('weibo').append(icon('weibo')).append("<a href='" + this.weibo + "' target='_blank'>" + this.weibo + "</a>").appendTo(this.$elm);
      }
      if (this.zhihu) {
        return this.$zhihu = build('zhihu').append(icon('zhihu')).append("<a href='" + this.zhihu + "' target='_blank'>" + this.zhihu + "</a>").appendTo(this.$elm);
      }
    };

    Member.load_data = function() {
      return jQuery.ajax({
        url: DATA_MEMBERS_URL,
        type: 'GET',
        dataType: 'json',
        success: (function(_this) {
          return function(res) {
            var member, obj, _i, _len, _results;
            _results = [];
            for (_i = 0, _len = res.length; _i < _len; _i++) {
              obj = res[_i];
              member = new Member(obj);
              _results.push(member.render());
            }
            return _results;
          };
        })(this)
      });
    };

    return Member;

  })();

  jQuery(function() {
    return Member.load_data();
  });

}).call(this);
